dist: trusty
language: java
# We now cache the Maven dependencies directory for faster builds
cache:
  apt: true
  directories:
  - $HOME/.m2
  - $HOME/.downloads
sudo: true
jdk: openjdk10
script:
  - jdk_switcher use openjdk10
  - export JAVA_HOME=$HOME/openjdk11
  - $TRAVIS_BUILD_DIR/install-jdk.sh --install openjdk11 --target $JAVA_HOME
  - # do stuff with open OpenJDK 11