dist: trusty
language: java
# We now cache the Maven dependencies directory for faster builds
#env:
#  - DOCKER_USER=baardl
#  - TAG=tmpTravis
cache:
  apt: true
  directories:
  - $HOME/.m2
  - $HOME/.downloads
sudo: true
jdk: openjdk11
script:
  # prepare qemu - multi platform build
  - docker run --rm --privileged multiarch/qemu-user-static:register --reset
  # build image
  - echo DOCKER_USER=$DOCKER_USERNAME
  - docker build -t baardl/bacnet-ip-agent-java:tmpTravis -f DockerfileRaspberryPi4 .
  - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
  - docker push baardl/bacnet-ip-agent-java:tmpTravis